version: '3.8'

services:
  user-service:
    build: ./service-a
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: mongodb://mongodb:27017/orbi
    depends_on:
      - rabbitmq
      - mongodb 
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - service_network

  notification-service:
    build: ./service-b
    ports:
      - "3001:3001"
      - "50051:50051"
    environment:
      MONGO_HOST: mongodb://mongodb:27017/orbi
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - service_network

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    networks:
      - service_network

  mongodb:
    image: "mongo:latest"
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - service_network

networks:
  service_network:
    driver: bridge